#!/bin/bash
# Script para diagnosticar el problema del frontend en EC2

echo "🔍 Diagnosticando problema del frontend en EC2..."
echo "============================================================"

# Configuración
EC2_IP="3.141.40.201"
EC2_USER="ubuntu"

echo "⚠️  Necesitas ejecutar estos comandos manualmente en el servidor EC2:"
echo ""
echo "1. Conectarse al servidor:"
echo "   ssh -i tu-clave.pem ubuntu@${EC2_IP}"
echo ""
echo "2. Ir al directorio del proyecto:"
echo "   cd /home/ubuntu/vantage-backend"
echo ""
echo "3. Verificar estado de contenedores:"
echo "   docker compose ps"
echo ""
echo "4. Ver logs del frontend:"
echo "   docker logs vantage-frontend-1 --tail 50"
echo ""
echo "5. Ver logs del backend:"
echo "   docker logs vantage-backend-1 --tail 20"
echo ""
echo "6. Probar conexión local:"
echo "   curl -v http://localhost:3000"
echo "   curl -v http://localhost:5002/health"
echo ""
echo "7. Verificar puertos en uso:"
echo "   sudo netstat -tlnp | grep :3000"
echo "   sudo netstat -tlnp | grep :5002"
echo ""
echo "8. Verificar firewall:"
echo "   sudo ufw status"
echo ""
echo "9. Si hay problemas, reiniciar contenedores:"
echo "   docker compose restart"
echo ""
echo "10. Si persiste el problema, reconstruir:"
echo "    docker compose down"
echo "    docker compose up --build -d"
echo ""
echo "🔧 POSIBLES CAUSAS DEL ERROR 500:"
echo ""
echo "   1. Contenedor frontend no inició correctamente"
echo "   2. Error en el build de Next.js"
echo "   3. Problema de memoria en el servidor"
echo "   4. Puerto bloqueado por firewall"
echo "   5. Error en la configuración de Tailwind CSS"
echo ""
echo "📋 COMANDOS DE DIAGNÓSTICO:"
echo ""
echo "   # Verificar recursos del sistema"
echo "   free -h"
echo "   df -h"
echo "   top"
echo ""
echo "   # Verificar logs de Docker"
echo "   docker system df"
echo "   docker logs vantage-frontend-1 --follow"
echo ""
echo "   # Verificar configuración de red"
echo "   ip addr show"
echo "   curl -I http://localhost:3000"
echo ""
echo "🎯 SOLUCIONES RÁPIDAS:"
echo ""
echo "   1. Reiniciar contenedores:"
echo "      docker compose restart"
echo ""
echo "   2. Limpiar caché y reconstruir:"
echo "      cd vantageai-frontend"
echo "      rm -rf .next"
echo "      cd .."
echo "      docker compose down"
echo "      docker compose up --build -d"
echo ""
echo "   3. Verificar memoria disponible:"
echo "      free -h"
echo "      # Si hay poca memoria, agregar swap"
echo ""
echo "   4. Verificar logs en tiempo real:"
echo "      docker logs vantage-frontend-1 --follow"
echo ""
echo "✅ DESPUÉS DE LA SOLUCIÓN:"
echo "   http://${EC2_IP}:3000 debería funcionar correctamente" 