version: '3.8'

services:
  # Backend Flask
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5002:5002"
    environment:
      - FLASK_APP=run_backend.py
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:////app/instance/vantageai.db
      - JWT_SECRET_KEY=your-super-secret-jwt-key-change-in-production
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - SEED_DB_ON_START=false
    volumes:
      - ./instance:/app/instance
      - ./static:/app/static
      - ./vantage_backend:/app/vantage_backend
    restart: unless-stopped

  # Frontend Next.js para desarrollo
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:5002
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true
    volumes:
      - ./vantageai-frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  instance:
    driver: local
  static:
    driver: local 