version: '3.8'

services:
  # PostgreSQL Database
  postgres-dev:
    image: postgres:15
    environment:
      - POSTGRES_DB=vantageai_dev
      - POSTGRES_USER=vantage_user
      - POSTGRES_PASSWORD=vantage_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Backend Flask (desarrollo)
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5002:5002"
    environment:
      - FLASK_APP=run_backend.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://vantage_user:vantage_password@postgres-dev:5432/vantageai_dev
      - JWT_SECRET_KEY=dev-secret-key
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    volumes:
      - ./instance:/app/instance
      - ./static:/app/static
      - ./vantage_backend:/app/vantage_backend
      - ./migrations:/app/migrations
      - ./run_backend.py:/app/run_backend.py
    command: ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=5002", "--reload"]
    restart: unless-stopped
    depends_on:
      - postgres-dev

  # Frontend Next.js (desarrollo)
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:5002
    volumes:
      - ./vantageai-frontend:/app
      - /app/node_modules
      - /app/.next
    command: ["npm", "run", "dev"]
    restart: unless-stopped
    depends_on:
      - backend-dev

volumes:
  postgres_data: 