services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=vantageai
      - POSTGRES_USER=vantage_user
      - POSTGRES_PASSWORD=vantage_password_secure
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vantage_user -d vantageai"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend Flask
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5002:5002"
    environment:
      - FLASK_APP=run_backend.py
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://vantage_user:vantage_password_secure@postgres:5432/vantageai
      - JWT_SECRET_KEY=your-super-secret-jwt-key-change-in-production
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000,https://your-amplify-domain.amplifyapp.com}
    volumes:
      - ./instance:/app/instance
      - ./static:/app/static
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  instance:
    driver: local
  static:
    driver: local 