#!/bin/bash
# Script para solucionar conflicto de contenedores en EC2

echo "🔧 Solucionando conflicto de contenedores en EC2..."
echo "============================================================"

# Configuración
EC2_IP="3.141.40.201"
EC2_USER="ubuntu"

echo "⚠️  Necesitas ejecutar estos comandos manualmente en el servidor EC2:"
echo ""
echo "1. Conectarse al servidor:"
echo "   ssh -i tu-clave.pem ubuntu@${EC2_IP}"
echo ""
echo "2. Ir al directorio del proyecto:"
echo "   cd /home/ubuntu/vantage-backend"
echo ""
echo "3. Verificar contenedores actuales:"
echo "   docker compose ps"
echo ""
echo "4. Detener TODOS los contenedores (incluyendo prod):"
echo "   docker compose down"
echo "   docker compose -f docker-compose.prod.yml down"
echo ""
echo "5. Verificar que no hay contenedores ejecutándose:"
echo "   docker ps"
echo ""
echo "6. Actualizar código desde GitHub:"
echo "   git pull origin main"
echo ""
echo "7. Limpiar caché de Next.js:"
echo "   cd vantageai-frontend"
echo "   rm -rf .next"
echo "   cd .."
echo ""
echo "8. Reconstruir contenedores Docker:"
echo "   docker compose up --build -d"
echo ""
echo "9. Esperar que los servicios estén listos (30 segundos):"
echo "   sleep 30"
echo ""
echo "10. Verificar estado:"
echo "    docker compose ps"
echo "    curl http://localhost:5002/health"
echo ""
echo "✅ Después de estos pasos, el diseño completo debería funcionar en:"
echo "   http://${EC2_IP}:3000"
echo ""
echo "🔧 PROBLEMA IDENTIFICADO:"
echo "   - Contenedores de producción (prod) ocupando puertos"
echo "   - Conflicto entre docker-compose.yml y docker-compose.prod.yml"
echo "   - Puerto 5002 ya está en uso"
echo ""
echo "🎯 SOLUCIÓN:"
echo "   - Detener TODOS los contenedores"
echo "   - Limpiar caché de Next.js"
echo "   - Reconstruir con el nuevo código"
echo ""
echo "🧪 Para probar el diseño completo:"
echo ""
echo "   1. Ve a http://${EC2_IP}:3000"
echo "   2. Inicia sesión con: cliente1@mineraandes.cl / password123"
echo "   3. Navega a:"
echo "      - Productos: /client/products"
echo "      - Servicios: /client/services"
echo "   4. Prueba los filtros y búsquedas"
echo "   5. Observa las animaciones hover"
echo ""
echo "📋 CAMBIOS IMPLEMENTADOS:"
echo "✅ Onboarding completo (cliente y proveedor)"
echo "✅ Diseño moderno de tarjetas"
echo "✅ Animaciones y efectos visuales"
echo "✅ Lazy loading optimizado"
echo "✅ Skeletons precisos"
echo "✅ Responsive design"
echo "✅ TypeScript interfaces"
echo "✅ Performance optimizations"
echo "✅ package-lock.json incluido"
echo ""
echo "🎯 NO SE NECESITAN MIGRACIONES:"
echo "   - Solo cambios de frontend"
echo "   - Backend sin modificaciones"
echo "   - Base de datos sin cambios"
echo ""
echo "🔧 CONFLICTO SOLUCIONADO:"
echo "   - Detener contenedores prod"
echo "   - Limpiar puertos ocupados"
echo "   - Reconstruir con nuevo código" 