#!/bin/bash
# Script para actualizar el servidor EC2 con package-lock.json incluido

echo "🔧 Actualizando servidor EC2 con package-lock.json incluido..."
echo "============================================================"

# Configuración
EC2_IP="3.141.40.201"
EC2_USER="ubuntu"

echo "⚠️  Necesitas ejecutar estos comandos manualmente en el servidor EC2:"
echo ""
echo "1. Conectarse al servidor:"
echo "   ssh -i tu-clave.pem ubuntu@${EC2_IP}"
echo ""
echo "2. Ir al directorio del proyecto:"
echo "   cd /home/ubuntu/vantage-backend"
echo ""
echo "3. Actualizar código desde GitHub (incluye package-lock.json):"
echo "   git pull origin main"
echo ""
echo "4. Limpiar caché de Next.js:"
echo "   cd vantageai-frontend"
echo "   rm -rf .next"
echo "   cd .."
echo ""
echo "5. Reconstruir contenedores Docker (ahora con package-lock.json):"
echo "   docker compose down"
echo "   docker compose up --build -d"
echo ""
echo "6. Esperar que los servicios estén listos (30 segundos):"
echo "   sleep 30"
echo ""
echo "7. Verificar estado:"
echo "   docker compose ps"
echo "   curl http://localhost:5002/health"
echo ""
echo "✅ Después de estos pasos, el diseño completo debería funcionar en:"
echo "   http://${EC2_IP}:3000"
echo ""
echo "🔧 PROBLEMA SOLUCIONADO:"
echo "   - Se agregó package-lock.json al repositorio"
echo "   - Docker build ahora funcionará correctamente"
echo "   - npm ci tendrá las dependencias bloqueadas"
echo ""
echo "🎨 NUEVAS CARACTERÍSTICAS DE DISEÑO:"
echo ""
echo "   PRODUCTOS:"
echo "   - Gradiente azul/púrpura en tarjetas"
echo "   - Badges destacados con estrellas doradas"
echo "   - Animaciones hover con transform"
echo "   - SKU badges mejorados"
echo "   - Información estructurada en cajas"
echo "   - Precios destacados en verde"
echo ""
echo "   SERVICIOS:"
echo "   - Gradiente púrpura/rosa en tarjetas"
echo "   - Iconos de llave inglesa"
echo "   - Badges de modalidad mejorados"
echo "   - Mismas animaciones que productos"
echo "   - Precios destacados en púrpura"
echo ""
echo "   MEJORAS GENERALES:"
echo "   - Skeletons precisos sin saltos"
echo "   - Lazy loading optimizado"
echo "   - Bordes redondeados (rounded-2xl)"
echo "   - Sombras mejoradas (hover:shadow-xl)"
echo "   - Tipografía mejorada"
echo "   - Espaciado estructurado"
echo ""
echo "🧪 Para probar el diseño completo:"
echo ""
echo "   1. Ve a http://${EC2_IP}:3000"
echo "   2. Inicia sesión con: cliente1@mineraandes.cl / password123"
echo "   3. Navega a:"
echo "      - Productos: /client/products"
echo "      - Servicios: /client/services"
echo "   4. Prueba los filtros y búsquedas"
echo "   5. Observa las animaciones hover"
echo ""
echo "📋 CAMBIOS IMPLEMENTADOS:"
echo "✅ Onboarding completo (cliente y proveedor)"
echo "✅ Diseño moderno de tarjetas"
echo "✅ Animaciones y efectos visuales"
echo "✅ Lazy loading optimizado"
echo "✅ Skeletons precisos"
echo "✅ Responsive design"
echo "✅ TypeScript interfaces"
echo "✅ Performance optimizations"
echo "✅ package-lock.json incluido"
echo ""
echo "🎯 NO SE NECESITAN MIGRACIONES:"
echo "   - Solo cambios de frontend"
echo "   - Backend sin modificaciones"
echo "   - Base de datos sin cambios"
echo ""
echo "🔧 DOCKER BUILD FIXED:"
echo "   - package-lock.json ahora disponible"
echo "   - npm ci funcionará correctamente"
echo "   - Dependencias bloqueadas para consistencia" 