#!/bin/bash
# Script para actualizar el servidor EC2 con onboarding completo funcionando

echo "🚀 Actualizando servidor EC2 con onboarding completo..."
echo "============================================================"

# Configuración
EC2_IP="3.141.40.201"
EC2_USER="ubuntu"

echo "⚠️  Necesitas ejecutar estos comandos manualmente en el servidor EC2:"
echo ""
echo "1. Conectarse al servidor:"
echo "   ssh -i tu-clave.pem ubuntu@${EC2_IP}"
echo ""
echo "2. Ir al directorio del proyecto:"
echo "   cd /home/ubuntu/vantage-backend"
echo ""
echo "3. Actualizar código desde GitHub:"
echo "   git pull origin main"
echo ""
echo "4. Limpiar caché de Next.js:"
echo "   cd vantageai-frontend"
echo "   rm -rf .next"
echo "   cd .."
echo ""
echo "5. Reconstruir contenedores Docker:"
echo "   docker compose down"
echo "   docker compose up --build -d"
echo ""
echo "6. Esperar que los servicios estén listos (30 segundos):"
echo "   sleep 30"
echo ""
echo "7. Verificar estado:"
echo "   docker compose ps"
echo "   curl http://localhost:5002/health"
echo ""
echo "✅ Después de estos pasos, el onboarding completo debería funcionar en:"
echo "   http://${EC2_IP}:3000"
echo ""
echo "🧪 Para probar el onboarding completo:"
echo ""
echo "   CLIENTE:"
echo "   1. Ve a http://${EC2_IP}:3000"
echo "   2. Inicia sesión con: cliente1@mineraandes.cl / password123"
echo "   3. Si has_completed_onboarding = False → verás onboarding del cliente"
echo "   4. Si has_completed_onboarding = True → verás dashboard del cliente"
echo ""
echo "   PROVEEDOR:"
echo "   1. Ve a http://${EC2_IP}:3000"
echo "   2. Inicia sesión con: juan.perez@solucioneshidraulicas.cl / password123"
echo "   3. Si has_completed_onboarding = False → verás onboarding del proveedor"
echo "   4. Si has_completed_onboarding = True → verás dashboard del proveedor"
echo ""
echo "🔄 Para resetear onboarding y probar desde cero:"
echo "   curl -X PUT http://localhost:5002/api/users/reset-onboarding \\"
echo "     -H 'Authorization: Bearer TU_TOKEN'"
echo ""
echo "📋 CAMBIOS IMPLEMENTADOS:"
echo "✅ Onboarding del cliente (4 pasos)"
echo "✅ Onboarding del proveedor (4 pasos)"
echo "✅ Redirección automática basada en has_completed_onboarding"
echo "✅ Tour guiado para cliente y proveedor"
echo "✅ Componentes separados para evitar bucles"
echo "✅ Debug logs para troubleshooting"
echo ""
echo "🎯 NO SE NECESITAN MIGRACIONES:"
echo "   - Se usa el campo has_completed_onboarding existente"
echo "   - No hay cambios en la estructura de la base de datos"
echo "   - Solo actualización de código frontend y backend" 