"""Initial database schema

Revision ID: 45443f2cf69f
Revises: 
Create Date: 2025-07-14 20:31:21.288524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45443f2cf69f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_table('client_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('about_us', sa.Text(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_companies'))
    )
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('product_limit', sa.Integer(), nullable=True),
    sa.Column('service_limit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans')),
    sa.UniqueConstraint('name', name=op.f('uq_plans_name'))
    )
    op.create_table('client_branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['client_companies.id'], name=op.f('fk_client_branches_company_id_client_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_branches'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('proveedor', 'cliente', 'administrador', name='user_roles'), nullable=False),
    sa.Column('status', sa.Enum('activo', 'suspendido', name='user_statuses'), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['client_branches.id'], name=op.f('fk_users_branch_id_client_branches')),
    sa.ForeignKeyConstraint(['company_id'], ['client_companies.id'], name=op.f('fk_users_company_id_client_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('providers_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('about_us', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('brochure_pdf_url', sa.String(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_providers_profile_plan_id_plans')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_providers_profile_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_providers_profile')),
    sa.UniqueConstraint('user_id', name=op.f('uq_providers_profile_user_id'))
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('technical_details', sa.Text(), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('borrador', 'activo', 'inactivo', name='product_statuses'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_products_category_id_categories')),
    sa.ForeignKeyConstraint(['provider_id'], ['providers_profile.id'], name=op.f('fk_products_provider_id_providers_profile')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_table('provider_certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers_profile.id'], name=op.f('fk_provider_certifications_provider_id_providers_profile')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_certifications'))
    )
    op.create_table('provider_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers_profile.id'], name=op.f('fk_provider_contacts_provider_id_providers_profile')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_contacts'))
    )
    op.create_table('quote_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_user_id', sa.Integer(), nullable=False),
    sa.Column('client_branch_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('producto', 'servicio', name='item_types'), nullable=False),
    sa.Column('item_name_snapshot', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_branch_id'], ['client_branches.id'], name=op.f('fk_quote_requests_client_branch_id_client_branches')),
    sa.ForeignKeyConstraint(['client_user_id'], ['users.id'], name=op.f('fk_quote_requests_client_user_id_users')),
    sa.ForeignKeyConstraint(['provider_id'], ['providers_profile.id'], name=op.f('fk_quote_requests_provider_id_providers_profile')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quote_requests'))
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('modality', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('borrador', 'activo', 'inactivo', name='service_statuses'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_services_category_id_categories')),
    sa.ForeignKeyConstraint(['provider_id'], ['providers_profile.id'], name=op.f('fk_services_provider_id_providers_profile')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services'))
    )
    op.create_table('quote_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_request_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['quote_request_id'], ['quote_requests.id'], name=op.f('fk_quote_attachments_quote_request_id_quote_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quote_attachments'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quote_attachments')
    op.drop_table('services')
    op.drop_table('quote_requests')
    op.drop_table('provider_contacts')
    op.drop_table('provider_certifications')
    op.drop_table('products')
    op.drop_table('providers_profile')
    op.drop_table('users')
    op.drop_table('client_branches')
    op.drop_table('plans')
    op.drop_table('client_companies')
    op.drop_table('categories')
    # ### end Alembic commands ###
