"""add quote_responses table

Revision ID: 6b4c612a2f85
Revises: 92599cce2f7f
Create Date: 2025-07-23 22:20:11.576025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b4c612a2f85'
down_revision = 'add_ia_data_to_quote_requests'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_request_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('response_pdf_url', sa.String(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('certifications_count', sa.Integer(), nullable=True),
    sa.Column('ia_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers_profile.id'], name=op.f('fk_quote_responses_provider_id_providers_profile')),
    sa.ForeignKeyConstraint(['quote_request_id'], ['quote_requests.id'], name=op.f('fk_quote_responses_quote_request_id_quote_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quote_responses'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quote_responses')
    # ### end Alembic commands ###
