"""Add is_featured column to products and services

Revision ID: 92599cce2f7f
Revises: 45443f2cf69f
Create Date: 2025-07-14 22:00:25.445314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92599cce2f7f'
down_revision = '45443f2cf69f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('is_featured')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('is_featured')

    # ### end Alembic commands ###
